//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/controllerbus/bus/api/api.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "../../controller/controller.pb.h"
#include "../../controller/exec/exec.pb.h"
#include "../../directive/directive.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto;
}  // extern "C"
namespace bus {
namespace api {
class Config;
struct ConfigDefaultTypeInternal;
extern ConfigDefaultTypeInternal _Config_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Config_class_data_;
class GetBusInfoRequest;
struct GetBusInfoRequestDefaultTypeInternal;
extern GetBusInfoRequestDefaultTypeInternal _GetBusInfoRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetBusInfoRequest_class_data_;
class GetBusInfoResponse;
struct GetBusInfoResponseDefaultTypeInternal;
extern GetBusInfoResponseDefaultTypeInternal _GetBusInfoResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetBusInfoResponse_class_data_;
}  // namespace api
}  // namespace bus
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace bus {
namespace api {

// ===================================================================


// -------------------------------------------------------------------

class GetBusInfoRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:bus.api.GetBusInfoRequest) */ {
 public:
  inline GetBusInfoRequest() : GetBusInfoRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetBusInfoRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetBusInfoRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetBusInfoRequest(::google::protobuf::internal::ConstantInitialized);

  inline GetBusInfoRequest(const GetBusInfoRequest& from) : GetBusInfoRequest(nullptr, from) {}
  inline GetBusInfoRequest(GetBusInfoRequest&& from) noexcept
      : GetBusInfoRequest(nullptr, ::std::move(from)) {}
  inline GetBusInfoRequest& operator=(const GetBusInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetBusInfoRequest& operator=(GetBusInfoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetBusInfoRequest& default_instance() {
    return *reinterpret_cast<const GetBusInfoRequest*>(
        &_GetBusInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GetBusInfoRequest& a, GetBusInfoRequest& b) { a.Swap(&b); }
  inline void Swap(GetBusInfoRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetBusInfoRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetBusInfoRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<GetBusInfoRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const GetBusInfoRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const GetBusInfoRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "bus.api.GetBusInfoRequest"; }

  explicit GetBusInfoRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetBusInfoRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetBusInfoRequest& from);
  GetBusInfoRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetBusInfoRequest&& from) noexcept
      : GetBusInfoRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:bus.api.GetBusInfoRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetBusInfoRequest_class_data_;
// -------------------------------------------------------------------

class Config final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:bus.api.Config) */ {
 public:
  inline Config() : Config(nullptr) {}
  ~Config() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Config* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Config));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Config(::google::protobuf::internal::ConstantInitialized);

  inline Config(const Config& from) : Config(nullptr, from) {}
  inline Config(Config&& from) noexcept
      : Config(nullptr, ::std::move(from)) {}
  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }
  inline Config& operator=(Config&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Config& default_instance() {
    return *reinterpret_cast<const Config*>(
        &_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Config& a, Config& b) { a.Swap(&b); }
  inline void Swap(Config* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Config* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Config* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Config>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Config& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Config& from) { Config::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Config* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "bus.api.Config"; }

  explicit Config(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Config(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Config& from);
  Config(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Config&& from) noexcept
      : Config(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEnableExecControllerFieldNumber = 1,
  };
  // bool enable_exec_controller = 1;
  void clear_enable_exec_controller() ;
  bool enable_exec_controller() const;
  void set_enable_exec_controller(bool value);

  private:
  bool _internal_enable_exec_controller() const;
  void _internal_set_enable_exec_controller(bool value);

  public:
  // @@protoc_insertion_point(class_scope:bus.api.Config)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Config& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool enable_exec_controller_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Config_class_data_;
// -------------------------------------------------------------------

class GetBusInfoResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:bus.api.GetBusInfoResponse) */ {
 public:
  inline GetBusInfoResponse() : GetBusInfoResponse(nullptr) {}
  ~GetBusInfoResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetBusInfoResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetBusInfoResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetBusInfoResponse(::google::protobuf::internal::ConstantInitialized);

  inline GetBusInfoResponse(const GetBusInfoResponse& from) : GetBusInfoResponse(nullptr, from) {}
  inline GetBusInfoResponse(GetBusInfoResponse&& from) noexcept
      : GetBusInfoResponse(nullptr, ::std::move(from)) {}
  inline GetBusInfoResponse& operator=(const GetBusInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetBusInfoResponse& operator=(GetBusInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetBusInfoResponse& default_instance() {
    return *reinterpret_cast<const GetBusInfoResponse*>(
        &_GetBusInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GetBusInfoResponse& a, GetBusInfoResponse& b) { a.Swap(&b); }
  inline void Swap(GetBusInfoResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetBusInfoResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetBusInfoResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetBusInfoResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetBusInfoResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetBusInfoResponse& from) { GetBusInfoResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetBusInfoResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "bus.api.GetBusInfoResponse"; }

  explicit GetBusInfoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetBusInfoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetBusInfoResponse& from);
  GetBusInfoResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetBusInfoResponse&& from) noexcept
      : GetBusInfoResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRunningControllersFieldNumber = 1,
    kRunningDirectivesFieldNumber = 2,
  };
  // repeated .controller.Info running_controllers = 1;
  int running_controllers_size() const;
  private:
  int _internal_running_controllers_size() const;

  public:
  void clear_running_controllers() ;
  ::controller::Info* PROTOBUF_NONNULL mutable_running_controllers(int index);
  ::google::protobuf::RepeatedPtrField<::controller::Info>* PROTOBUF_NONNULL mutable_running_controllers();

  private:
  const ::google::protobuf::RepeatedPtrField<::controller::Info>& _internal_running_controllers() const;
  ::google::protobuf::RepeatedPtrField<::controller::Info>* PROTOBUF_NONNULL _internal_mutable_running_controllers();
  public:
  const ::controller::Info& running_controllers(int index) const;
  ::controller::Info* PROTOBUF_NONNULL add_running_controllers();
  const ::google::protobuf::RepeatedPtrField<::controller::Info>& running_controllers() const;
  // repeated .directive.DirectiveState running_directives = 2;
  int running_directives_size() const;
  private:
  int _internal_running_directives_size() const;

  public:
  void clear_running_directives() ;
  ::directive::DirectiveState* PROTOBUF_NONNULL mutable_running_directives(int index);
  ::google::protobuf::RepeatedPtrField<::directive::DirectiveState>* PROTOBUF_NONNULL mutable_running_directives();

  private:
  const ::google::protobuf::RepeatedPtrField<::directive::DirectiveState>& _internal_running_directives() const;
  ::google::protobuf::RepeatedPtrField<::directive::DirectiveState>* PROTOBUF_NONNULL _internal_mutable_running_directives();
  public:
  const ::directive::DirectiveState& running_directives(int index) const;
  ::directive::DirectiveState* PROTOBUF_NONNULL add_running_directives();
  const ::google::protobuf::RepeatedPtrField<::directive::DirectiveState>& running_directives() const;
  // @@protoc_insertion_point(class_scope:bus.api.GetBusInfoResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GetBusInfoResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::controller::Info > running_controllers_;
    ::google::protobuf::RepeatedPtrField< ::directive::DirectiveState > running_directives_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetBusInfoResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Config

// bool enable_exec_controller = 1;
inline void Config::clear_enable_exec_controller() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_exec_controller_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool Config::enable_exec_controller() const {
  // @@protoc_insertion_point(field_get:bus.api.Config.enable_exec_controller)
  return _internal_enable_exec_controller();
}
inline void Config::set_enable_exec_controller(bool value) {
  _internal_set_enable_exec_controller(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:bus.api.Config.enable_exec_controller)
}
inline bool Config::_internal_enable_exec_controller() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enable_exec_controller_;
}
inline void Config::_internal_set_enable_exec_controller(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_exec_controller_ = value;
}

// -------------------------------------------------------------------

// GetBusInfoRequest

// -------------------------------------------------------------------

// GetBusInfoResponse

// repeated .controller.Info running_controllers = 1;
inline int GetBusInfoResponse::_internal_running_controllers_size() const {
  return _internal_running_controllers().size();
}
inline int GetBusInfoResponse::running_controllers_size() const {
  return _internal_running_controllers_size();
}
inline ::controller::Info* PROTOBUF_NONNULL GetBusInfoResponse::mutable_running_controllers(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:bus.api.GetBusInfoResponse.running_controllers)
  return _internal_mutable_running_controllers()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::controller::Info>* PROTOBUF_NONNULL GetBusInfoResponse::mutable_running_controllers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:bus.api.GetBusInfoResponse.running_controllers)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_running_controllers();
}
inline const ::controller::Info& GetBusInfoResponse::running_controllers(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:bus.api.GetBusInfoResponse.running_controllers)
  return _internal_running_controllers().Get(index);
}
inline ::controller::Info* PROTOBUF_NONNULL GetBusInfoResponse::add_running_controllers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::controller::Info* _add =
      _internal_mutable_running_controllers()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:bus.api.GetBusInfoResponse.running_controllers)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::controller::Info>& GetBusInfoResponse::running_controllers() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:bus.api.GetBusInfoResponse.running_controllers)
  return _internal_running_controllers();
}
inline const ::google::protobuf::RepeatedPtrField<::controller::Info>&
GetBusInfoResponse::_internal_running_controllers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.running_controllers_;
}
inline ::google::protobuf::RepeatedPtrField<::controller::Info>* PROTOBUF_NONNULL
GetBusInfoResponse::_internal_mutable_running_controllers() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.running_controllers_;
}

// repeated .directive.DirectiveState running_directives = 2;
inline int GetBusInfoResponse::_internal_running_directives_size() const {
  return _internal_running_directives().size();
}
inline int GetBusInfoResponse::running_directives_size() const {
  return _internal_running_directives_size();
}
inline ::directive::DirectiveState* PROTOBUF_NONNULL GetBusInfoResponse::mutable_running_directives(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:bus.api.GetBusInfoResponse.running_directives)
  return _internal_mutable_running_directives()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::directive::DirectiveState>* PROTOBUF_NONNULL GetBusInfoResponse::mutable_running_directives()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:bus.api.GetBusInfoResponse.running_directives)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_running_directives();
}
inline const ::directive::DirectiveState& GetBusInfoResponse::running_directives(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:bus.api.GetBusInfoResponse.running_directives)
  return _internal_running_directives().Get(index);
}
inline ::directive::DirectiveState* PROTOBUF_NONNULL GetBusInfoResponse::add_running_directives()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::directive::DirectiveState* _add =
      _internal_mutable_running_directives()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:bus.api.GetBusInfoResponse.running_directives)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::directive::DirectiveState>& GetBusInfoResponse::running_directives() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:bus.api.GetBusInfoResponse.running_directives)
  return _internal_running_directives();
}
inline const ::google::protobuf::RepeatedPtrField<::directive::DirectiveState>&
GetBusInfoResponse::_internal_running_directives() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.running_directives_;
}
inline ::google::protobuf::RepeatedPtrField<::directive::DirectiveState>* PROTOBUF_NONNULL
GetBusInfoResponse::_internal_mutable_running_directives() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.running_directives_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace bus


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto_2epb_2eh
