//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/controllerbus/bus/api/api.proto
// Protobuf C++ Version: 6.33.4

#include "api.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace bus {
namespace api {
template <typename>
PROTOBUF_CONSTEXPR GetBusInfoRequest::GetBusInfoRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(GetBusInfoRequest_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct GetBusInfoRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBusInfoRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBusInfoRequestDefaultTypeInternal() {}
  union {
    GetBusInfoRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBusInfoRequestDefaultTypeInternal _GetBusInfoRequest_default_instance_;

inline constexpr Config::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        enable_exec_controller_{false} {}

template <typename>
PROTOBUF_CONSTEXPR Config::Config(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Config_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigDefaultTypeInternal() {}
  union {
    Config _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigDefaultTypeInternal _Config_default_instance_;

inline constexpr GetBusInfoResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        running_controllers_{},
        running_directives_{} {}

template <typename>
PROTOBUF_CONSTEXPR GetBusInfoResponse::GetBusInfoResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetBusInfoResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetBusInfoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBusInfoResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBusInfoResponseDefaultTypeInternal() {}
  union {
    GetBusInfoResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBusInfoResponseDefaultTypeInternal _GetBusInfoResponse_default_instance_;
}  // namespace api
}  // namespace bus
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::bus::api::Config, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::bus::api::Config, _impl_.enable_exec_controller_),
        0,
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::bus::api::GetBusInfoResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::bus::api::GetBusInfoResponse, _impl_.running_controllers_),
        PROTOBUF_FIELD_OFFSET(::bus::api::GetBusInfoResponse, _impl_.running_directives_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::bus::api::Config)},
        {5, sizeof(::bus::api::GetBusInfoRequest)},
        {6, sizeof(::bus::api::GetBusInfoResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::bus::api::_Config_default_instance_._instance,
    &::bus::api::_GetBusInfoRequest_default_instance_._instance,
    &::bus::api::_GetBusInfoResponse_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n;github.com/aperturerobotics/controller"
    "bus/bus/api/api.proto\022\007bus.api\032Egithub.c"
    "om/aperturerobotics/controllerbus/contro"
    "ller/controller.proto\032Dgithub.com/apertu"
    "rerobotics/controllerbus/controller/exec"
    "/exec.proto\032Cgithub.com/aperturerobotics"
    "/controllerbus/directive/directive.proto"
    "\"(\n\006Config\022\036\n\026enable_exec_controller\030\001 \001"
    "(\010\"\023\n\021GetBusInfoRequest\"z\n\022GetBusInfoRes"
    "ponse\022-\n\023running_controllers\030\001 \003(\0132\020.con"
    "troller.Info\0225\n\022running_directives\030\002 \003(\013"
    "2\031.directive.DirectiveState2\306\001\n\024Controll"
    "erBusService\022G\n\nGetBusInfo\022\032.bus.api.Get"
    "BusInfoRequest\032\033.bus.api.GetBusInfoRespo"
    "nse\"\000\022e\n\016ExecController\022&.controller.exe"
    "c.ExecControllerRequest\032\'.controller.exe"
    "c.ExecControllerResponse\"\0000\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto_deps[3] = {
        &::descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fcontroller_2eproto,
        &::descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto,
        &::descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fdirective_2fdirective_2eproto,
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto = {
    false,
    false,
    676,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto,
    "github.com/aperturerobotics/controllerbus/bus/api/api.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto_once,
    descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto_deps,
    3,
    3,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto,
};
namespace bus {
namespace api {
// ===================================================================

class Config::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Config>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Config, _impl_._has_bits_);
};

Config::Config(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Config_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bus.api.Config)
}
Config::Config(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Config& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Config_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Config::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Config::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.enable_exec_controller_ = {};
}
Config::~Config() {
  // @@protoc_insertion_point(destructor:bus.api.Config)
  SharedDtor(*this);
}
inline void Config::SharedDtor(MessageLite& self) {
  Config& this_ = static_cast<Config&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Config::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Config(arena);
}
constexpr auto Config::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Config),
                                            alignof(Config));
}
constexpr auto Config::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Config_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Config::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Config>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Config::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Config>(), &Config::ByteSizeLong,
              &Config::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Config, _impl_._cached_size_),
          false,
      },
      &Config::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Config_class_data_ =
        Config::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Config::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Config_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Config_class_data_.tc_table);
  return Config_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
Config::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Config, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Config_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bus::api::Config>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool enable_exec_controller = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Config, _impl_.enable_exec_controller_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(Config, _impl_.enable_exec_controller_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool enable_exec_controller = 1;
    {PROTOBUF_FIELD_OFFSET(Config, _impl_.enable_exec_controller_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Config::Clear() {
// @@protoc_insertion_point(message_clear_start:bus.api.Config)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.enable_exec_controller_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Config::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Config& this_ = static_cast<const Config&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Config::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Config& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:bus.api.Config)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool enable_exec_controller = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_enable_exec_controller() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_enable_exec_controller(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bus.api.Config)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Config::ByteSizeLong(const MessageLite& base) {
  const Config& this_ = static_cast<const Config&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Config::ByteSizeLong() const {
  const Config& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:bus.api.Config)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bool enable_exec_controller = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_enable_exec_controller() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Config::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Config*>(&to_msg);
  auto& from = static_cast<const Config&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:bus.api.Config)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_enable_exec_controller() != 0) {
      _this->_impl_.enable_exec_controller_ = from._impl_.enable_exec_controller_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Config::CopyFrom(const Config& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:bus.api.Config)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Config::InternalSwap(Config* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.enable_exec_controller_, other->_impl_.enable_exec_controller_);
}

::google::protobuf::Metadata Config::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBusInfoRequest::_Internal {
 public:
};

GetBusInfoRequest::GetBusInfoRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, GetBusInfoRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:bus.api.GetBusInfoRequest)
}
GetBusInfoRequest::GetBusInfoRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetBusInfoRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, GetBusInfoRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBusInfoRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:bus.api.GetBusInfoRequest)
}

inline void* PROTOBUF_NONNULL GetBusInfoRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetBusInfoRequest(arena);
}
constexpr auto GetBusInfoRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetBusInfoRequest),
                                            alignof(GetBusInfoRequest));
}
constexpr auto GetBusInfoRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetBusInfoRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetBusInfoRequest::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<GetBusInfoRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetBusInfoRequest::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<GetBusInfoRequest>(), &GetBusInfoRequest::ByteSizeLong,
              &GetBusInfoRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetBusInfoRequest, _impl_._cached_size_),
          false,
      },
      &GetBusInfoRequest::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetBusInfoRequest_class_data_ =
        GetBusInfoRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetBusInfoRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetBusInfoRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetBusInfoRequest_class_data_.tc_table);
  return GetBusInfoRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
GetBusInfoRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GetBusInfoRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bus::api::GetBusInfoRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata GetBusInfoRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBusInfoResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetBusInfoResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_._has_bits_);
};

void GetBusInfoResponse::clear_running_controllers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.running_controllers_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
void GetBusInfoResponse::clear_running_directives() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.running_directives_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
GetBusInfoResponse::GetBusInfoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetBusInfoResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bus.api.GetBusInfoResponse)
}
PROTOBUF_NDEBUG_INLINE GetBusInfoResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::bus::api::GetBusInfoResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        running_controllers_{visibility, arena, from.running_controllers_},
        running_directives_{visibility, arena, from.running_directives_} {}

GetBusInfoResponse::GetBusInfoResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetBusInfoResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetBusInfoResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBusInfoResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:bus.api.GetBusInfoResponse)
}
PROTOBUF_NDEBUG_INLINE GetBusInfoResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        running_controllers_{visibility, arena},
        running_directives_{visibility, arena} {}

inline void GetBusInfoResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetBusInfoResponse::~GetBusInfoResponse() {
  // @@protoc_insertion_point(destructor:bus.api.GetBusInfoResponse)
  SharedDtor(*this);
}
inline void GetBusInfoResponse::SharedDtor(MessageLite& self) {
  GetBusInfoResponse& this_ = static_cast<GetBusInfoResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetBusInfoResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetBusInfoResponse(arena);
}
constexpr auto GetBusInfoResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_.running_controllers_) +
          decltype(GetBusInfoResponse::_impl_.running_controllers_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_.running_directives_) +
          decltype(GetBusInfoResponse::_impl_.running_directives_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(GetBusInfoResponse), alignof(GetBusInfoResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&GetBusInfoResponse::PlacementNew_,
                                 sizeof(GetBusInfoResponse),
                                 alignof(GetBusInfoResponse));
  }
}
constexpr auto GetBusInfoResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetBusInfoResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetBusInfoResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetBusInfoResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetBusInfoResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetBusInfoResponse>(), &GetBusInfoResponse::ByteSizeLong,
              &GetBusInfoResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_._cached_size_),
          false,
      },
      &GetBusInfoResponse::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetBusInfoResponse_class_data_ =
        GetBusInfoResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetBusInfoResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetBusInfoResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetBusInfoResponse_class_data_.tc_table);
  return GetBusInfoResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
GetBusInfoResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GetBusInfoResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bus::api::GetBusInfoResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .directive.DirectiveState running_directives = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_.running_directives_)}},
    // repeated .controller.Info running_controllers = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_.running_controllers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .controller.Info running_controllers = 1;
    {PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_.running_controllers_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .directive.DirectiveState running_directives = 2;
    {PROTOBUF_FIELD_OFFSET(GetBusInfoResponse, _impl_.running_directives_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::controller::Info>()},
      {::_pbi::TcParser::GetTable<::directive::DirectiveState>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void GetBusInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:bus.api.GetBusInfoResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.running_controllers_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.running_directives_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetBusInfoResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetBusInfoResponse& this_ = static_cast<const GetBusInfoResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetBusInfoResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetBusInfoResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:bus.api.GetBusInfoResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .controller.Info running_controllers = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_running_controllers_size());
         i < n; i++) {
      const auto& repfield = this_._internal_running_controllers().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated .directive.DirectiveState running_directives = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_running_directives_size());
         i < n; i++) {
      const auto& repfield = this_._internal_running_directives().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bus.api.GetBusInfoResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetBusInfoResponse::ByteSizeLong(const MessageLite& base) {
  const GetBusInfoResponse& this_ = static_cast<const GetBusInfoResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetBusInfoResponse::ByteSizeLong() const {
  const GetBusInfoResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:bus.api.GetBusInfoResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .controller.Info running_controllers = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_running_controllers_size();
      for (const auto& msg : this_._internal_running_controllers()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .directive.DirectiveState running_directives = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_running_directives_size();
      for (const auto& msg : this_._internal_running_directives()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetBusInfoResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GetBusInfoResponse*>(&to_msg);
  auto& from = static_cast<const GetBusInfoResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:bus.api.GetBusInfoResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_running_controllers()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_running_controllers());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_running_directives()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_running_directives());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GetBusInfoResponse::CopyFrom(const GetBusInfoResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:bus.api.GetBusInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetBusInfoResponse::InternalSwap(GetBusInfoResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.running_controllers_.InternalSwap(&other->_impl_.running_controllers_);
  _impl_.running_directives_.InternalSwap(&other->_impl_.running_directives_);
}

::google::protobuf::Metadata GetBusInfoResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace bus
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fbus_2fapi_2fapi_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
