// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/controllerbus/bus/api/api.proto

package bus_api

import (
	context "context"
	fmt "fmt"
	controller "github.com/aperturerobotics/controllerbus/controller"
	exec "github.com/aperturerobotics/controllerbus/controller/exec"
	directive "github.com/aperturerobotics/controllerbus/directive"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GetBusInfoRequest is the request type for GetBusInfo.
type GetBusInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBusInfoRequest) Reset()         { *m = GetBusInfoRequest{} }
func (m *GetBusInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetBusInfoRequest) ProtoMessage()    {}
func (*GetBusInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fbbe4e64990f1, []int{0}
}

func (m *GetBusInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusInfoRequest.Unmarshal(m, b)
}
func (m *GetBusInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetBusInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusInfoRequest.Merge(m, src)
}
func (m *GetBusInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetBusInfoRequest.Size(m)
}
func (m *GetBusInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusInfoRequest proto.InternalMessageInfo

// GetBusInfoResponse is the response type for GetBusInfo.
type GetBusInfoResponse struct {
	// RunningControllers is the list of running controllers.
	RunningControllers []*controller.Info `protobuf:"bytes,1,rep,name=running_controllers,json=runningControllers,proto3" json:"running_controllers,omitempty"`
	// RunningDirectives is the list of running directives.
	RunningDirectives    []*directive.DirectiveState `protobuf:"bytes,2,rep,name=running_directives,json=runningDirectives,proto3" json:"running_directives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetBusInfoResponse) Reset()         { *m = GetBusInfoResponse{} }
func (m *GetBusInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetBusInfoResponse) ProtoMessage()    {}
func (*GetBusInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9fbbe4e64990f1, []int{1}
}

func (m *GetBusInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusInfoResponse.Unmarshal(m, b)
}
func (m *GetBusInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetBusInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusInfoResponse.Merge(m, src)
}
func (m *GetBusInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetBusInfoResponse.Size(m)
}
func (m *GetBusInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusInfoResponse proto.InternalMessageInfo

func (m *GetBusInfoResponse) GetRunningControllers() []*controller.Info {
	if m != nil {
		return m.RunningControllers
	}
	return nil
}

func (m *GetBusInfoResponse) GetRunningDirectives() []*directive.DirectiveState {
	if m != nil {
		return m.RunningDirectives
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBusInfoRequest)(nil), "bus.api.GetBusInfoRequest")
	proto.RegisterType((*GetBusInfoResponse)(nil), "bus.api.GetBusInfoResponse")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/controllerbus/bus/api/api.proto", fileDescriptor_cb9fbbe4e64990f1)
}

var fileDescriptor_cb9fbbe4e64990f1 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4e, 0xc3, 0x30,
	0x0c, 0xc6, 0x29, 0x48, 0x20, 0x05, 0x09, 0xb1, 0x8c, 0xc3, 0x28, 0x17, 0xd4, 0x03, 0x70, 0x4a,
	0xd1, 0x38, 0x72, 0x62, 0x7f, 0x34, 0xb8, 0x6e, 0x0f, 0x30, 0xb5, 0xc1, 0x8c, 0x48, 0x23, 0x09,
	0xb1, 0x33, 0xed, 0x75, 0x78, 0x19, 0x9e, 0x0b, 0x2d, 0x6d, 0x97, 0x22, 0x90, 0x98, 0x38, 0xb8,
	0x72, 0x9d, 0xcf, 0x3f, 0xfb, 0x93, 0xd9, 0xfd, 0x42, 0xd1, 0xab, 0x2f, 0x85, 0x34, 0x6f, 0x79,
	0x61, 0xc1, 0x91, 0x77, 0xe0, 0x4c, 0x69, 0x48, 0x49, 0xcc, 0xa5, 0xd1, 0xe4, 0xcc, 0x72, 0x09,
	0xae, 0xf4, 0x98, 0x6f, 0xa2, 0xb0, 0x6a, 0x13, 0xc2, 0x3a, 0x43, 0x86, 0x1f, 0x95, 0x1e, 0x45,
	0x61, 0x55, 0x3a, 0xde, 0x9d, 0x12, 0xff, 0x5a, 0x69, 0xc5, 0x4b, 0x47, 0xff, 0xc2, 0xc0, 0x1a,
	0x64, 0xf8, 0xd4, 0x94, 0xe1, 0xee, 0x94, 0x67, 0xe5, 0x40, 0x92, 0x5a, 0x41, 0xcc, 0x2a, 0x48,
	0xd6, 0x65, 0x9d, 0x09, 0xd0, 0xc0, 0xe3, 0x93, 0x7e, 0x31, 0x53, 0x78, 0xf7, 0x80, 0x94, 0x7d,
	0x24, 0x8c, 0xb7, 0xab, 0x68, 0x8d, 0x46, 0xe0, 0x0f, 0xac, 0xeb, 0xbc, 0xd6, 0x4a, 0x2f, 0xe6,
	0x11, 0x8f, 0xbd, 0xe4, 0xf2, 0xe0, 0xe6, 0xb8, 0x7f, 0x2a, 0x5a, 0x36, 0x43, 0x1b, 0xaf, 0xc5,
	0xc3, 0xa8, 0xe5, 0x8f, 0xac, 0xa9, 0xce, 0xb7, 0x9b, 0x60, 0x6f, 0x3f, 0x10, 0xce, 0x45, 0x5c,
	0x6e, 0xd4, 0x64, 0x33, 0x2a, 0x08, 0xa6, 0x9d, 0xba, 0x69, 0x5b, 0xc6, 0xfe, 0x67, 0xc2, 0xce,
	0x22, 0x79, 0xe0, 0x71, 0x06, 0x6e, 0xa5, 0x24, 0xf0, 0x09, 0x63, 0x71, 0x77, 0x9e, 0x8a, 0xfa,
	0x76, 0xe2, 0x87, 0xcd, 0xf4, 0xe2, 0xd7, 0xb7, 0xca, 0x6c, 0xb6, 0xc7, 0x81, 0x9d, 0x8c, 0xd7,
	0x20, 0xe3, 0x10, 0x7e, 0xd5, 0xf6, 0x18, 0x2e, 0xf1, 0x5d, 0xd0, 0x80, 0xaf, 0xff, 0xd4, 0x35,
	0x43, 0x6e, 0x93, 0xf2, 0x30, 0x1c, 0xe2, 0xee, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x73, 0x3a,
	0x94, 0xa2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ControllerBusServiceClient is the client API for ControllerBusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerBusServiceClient interface {
	// GetBusInfo requests information about the controller bus.
	GetBusInfo(ctx context.Context, in *GetBusInfoRequest, opts ...grpc.CallOption) (*GetBusInfoResponse, error)
	// ExecController executes a controller configuration on the bus.
	ExecController(ctx context.Context, in *exec.ExecControllerRequest, opts ...grpc.CallOption) (ControllerBusService_ExecControllerClient, error)
}

type controllerBusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerBusServiceClient(cc grpc.ClientConnInterface) ControllerBusServiceClient {
	return &controllerBusServiceClient{cc}
}

func (c *controllerBusServiceClient) GetBusInfo(ctx context.Context, in *GetBusInfoRequest, opts ...grpc.CallOption) (*GetBusInfoResponse, error) {
	out := new(GetBusInfoResponse)
	err := c.cc.Invoke(ctx, "/bus.api.ControllerBusService/GetBusInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerBusServiceClient) ExecController(ctx context.Context, in *exec.ExecControllerRequest, opts ...grpc.CallOption) (ControllerBusService_ExecControllerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControllerBusService_serviceDesc.Streams[0], "/bus.api.ControllerBusService/ExecController", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerBusServiceExecControllerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControllerBusService_ExecControllerClient interface {
	Recv() (*exec.ExecControllerResponse, error)
	grpc.ClientStream
}

type controllerBusServiceExecControllerClient struct {
	grpc.ClientStream
}

func (x *controllerBusServiceExecControllerClient) Recv() (*exec.ExecControllerResponse, error) {
	m := new(exec.ExecControllerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControllerBusServiceServer is the server API for ControllerBusService service.
type ControllerBusServiceServer interface {
	// GetBusInfo requests information about the controller bus.
	GetBusInfo(context.Context, *GetBusInfoRequest) (*GetBusInfoResponse, error)
	// ExecController executes a controller configuration on the bus.
	ExecController(*exec.ExecControllerRequest, ControllerBusService_ExecControllerServer) error
}

// UnimplementedControllerBusServiceServer can be embedded to have forward compatible implementations.
type UnimplementedControllerBusServiceServer struct {
}

func (*UnimplementedControllerBusServiceServer) GetBusInfo(ctx context.Context, req *GetBusInfoRequest) (*GetBusInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusInfo not implemented")
}
func (*UnimplementedControllerBusServiceServer) ExecController(req *exec.ExecControllerRequest, srv ControllerBusService_ExecControllerServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecController not implemented")
}

func RegisterControllerBusServiceServer(s *grpc.Server, srv ControllerBusServiceServer) {
	s.RegisterService(&_ControllerBusService_serviceDesc, srv)
}

func _ControllerBusService_GetBusInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerBusServiceServer).GetBusInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bus.api.ControllerBusService/GetBusInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerBusServiceServer).GetBusInfo(ctx, req.(*GetBusInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerBusService_ExecController_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(exec.ExecControllerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerBusServiceServer).ExecController(m, &controllerBusServiceExecControllerServer{stream})
}

type ControllerBusService_ExecControllerServer interface {
	Send(*exec.ExecControllerResponse) error
	grpc.ServerStream
}

type controllerBusServiceExecControllerServer struct {
	grpc.ServerStream
}

func (x *controllerBusServiceExecControllerServer) Send(m *exec.ExecControllerResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ControllerBusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bus.api.ControllerBusService",
	HandlerType: (*ControllerBusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBusInfo",
			Handler:    _ControllerBusService_GetBusInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecController",
			Handler:       _ControllerBusService_ExecController_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/aperturerobotics/controllerbus/bus/api/api.proto",
}
