// @generated
// This file is @generated by prost-build.
/// Config are configuration arguments.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    /// EnableExecController enables the exec controller API.
    #[prost(bool, tag="1")]
    pub enable_exec_controller: bool,
}
/// GetBusInfoRequest is the request type for GetBusInfo.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBusInfoRequest {
}
/// GetBusInfoResponse is the response type for GetBusInfo.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBusInfoResponse {
    /// RunningControllers is the list of running controllers.
    #[prost(message, repeated, tag="1")]
    pub running_controllers: ::prost::alloc::vec::Vec<super::super::controller::Info>,
    /// RunningDirectives is the list of running directives.
    #[prost(message, repeated, tag="2")]
    pub running_directives: ::prost::alloc::vec::Vec<super::super::directive::DirectiveState>,
}
// @@protoc_insertion_point(module)
