// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/controllerbus/bus/api/controller/controller.proto (package bus.api.controller, syntax proto3)
/* eslint-disable */

import {
  createMessageType,
  Message,
  MessageType,
  PartialFieldInfo,
} from '@aptre/protobuf-es-lite'
import { Config as Config$1 } from '../api_pb.js'

export const protobufPackage = 'bus.api.controller'

/**
 * Config configures the API.
 *
 * @generated from message bus.api.controller.Config
 */
export interface Config extends Message<Config> {
  /**
   * ListenAddr is the address to listen on for connections.
   *
   * @generated from field: string listen_addr = 1;
   */
  listenAddr?: string
  /**
   * BusApiConfig are options for controller bus api.
   *
   * @generated from field: bus.api.Config bus_api_config = 2;
   */
  busApiConfig?: Config$1
}

export const Config: MessageType<Config> = createMessageType({
  typeName: 'bus.api.controller.Config',
  fields: [
    {
      no: 1,
      name: 'listen_addr',
      kind: 'scalar',
      T: 9 /* ScalarType.STRING */,
    },
    { no: 2, name: 'bus_api_config', kind: 'message', T: Config$1 },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
