// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/controllerbus/bus/api/controller/controller.proto

package controllerbus_grpc_controller

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config configures the GRPC API.
type Config struct {
	// ListenAddr is the address to listen on for connections.
	ListenAddr string `protobuf:"bytes,1,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	// EnableExecController enables the exec controller API.
	EnableExecController bool     `protobuf:"varint,2,opt,name=enable_exec_controller,json=enableExecController,proto3" json:"enable_exec_controller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d5967c7e353488, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *Config) GetEnableExecController() bool {
	if m != nil {
		return m.EnableExecController
	}
	return false
}

func init() {
	proto.RegisterType((*Config)(nil), "controllerbus.grpc.controller.Config")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/controllerbus/bus/api/controller/controller.proto", fileDescriptor_97d5967c7e353488)
}

var fileDescriptor_97d5967c7e353488 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xf2, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x48, 0x2d, 0x2a, 0x29, 0x2d, 0x4a, 0x2d,
	0xca, 0x4f, 0xca, 0x2f, 0xc9, 0x4c, 0x2e, 0xd6, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0xc9,
	0x49, 0x2d, 0x4a, 0x2a, 0x2d, 0xd6, 0x07, 0xe1, 0xc4, 0x82, 0x4c, 0x24, 0x51, 0x24, 0xa6, 0x5e,
	0x41, 0x51, 0x7e, 0x49, 0xbe, 0x90, 0x2c, 0x8a, 0x16, 0xbd, 0xf4, 0xa2, 0x82, 0x64, 0x3d, 0x84,
	0x90, 0x52, 0x3c, 0x17, 0x9b, 0x73, 0x7e, 0x5e, 0x5a, 0x66, 0xba, 0x90, 0x3c, 0x17, 0x77, 0x4e,
	0x66, 0x71, 0x49, 0x6a, 0x5e, 0x7c, 0x62, 0x4a, 0x4a, 0x91, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x17, 0x44, 0xc8, 0x31, 0x25, 0xa5, 0x48, 0xc8, 0x84, 0x4b, 0x2c, 0x35, 0x2f, 0x31, 0x29,
	0x27, 0x35, 0x3e, 0xb5, 0x22, 0x35, 0x39, 0x1e, 0x61, 0x88, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47,
	0x90, 0x08, 0x44, 0xd6, 0xb5, 0x22, 0x35, 0xd9, 0x19, 0x61, 0x27, 0x1b, 0xd8, 0x19, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x6d, 0xe5, 0xfd, 0xd7, 0x00, 0x00, 0x00,
}
