//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/controllerbus/example/boilerplate/v1/boilerplate.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2fcontrollerbus_2fexample_2fboilerplate_2fv1_2fboilerplate_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2fcontrollerbus_2fexample_2fboilerplate_2fv1_2fboilerplate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2fcontrollerbus_2fexample_2fboilerplate_2fv1_2fboilerplate_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fexample_2fboilerplate_2fv1_2fboilerplate_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fexample_2fboilerplate_2fv1_2fboilerplate_2eproto;
}  // extern "C"
namespace boilerplate {
namespace v1 {
class Boilerplate;
struct BoilerplateDefaultTypeInternal;
extern BoilerplateDefaultTypeInternal _Boilerplate_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Boilerplate_class_data_;
class BoilerplateResult;
struct BoilerplateResultDefaultTypeInternal;
extern BoilerplateResultDefaultTypeInternal _BoilerplateResult_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BoilerplateResult_class_data_;
}  // namespace v1
}  // namespace boilerplate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace boilerplate {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class BoilerplateResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:boilerplate.v1.BoilerplateResult) */ {
 public:
  inline BoilerplateResult() : BoilerplateResult(nullptr) {}
  ~BoilerplateResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BoilerplateResult* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BoilerplateResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BoilerplateResult(::google::protobuf::internal::ConstantInitialized);

  inline BoilerplateResult(const BoilerplateResult& from) : BoilerplateResult(nullptr, from) {}
  inline BoilerplateResult(BoilerplateResult&& from) noexcept
      : BoilerplateResult(nullptr, ::std::move(from)) {}
  inline BoilerplateResult& operator=(const BoilerplateResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline BoilerplateResult& operator=(BoilerplateResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BoilerplateResult& default_instance() {
    return *reinterpret_cast<const BoilerplateResult*>(
        &_BoilerplateResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BoilerplateResult& a, BoilerplateResult& b) { a.Swap(&b); }
  inline void Swap(BoilerplateResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BoilerplateResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BoilerplateResult* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BoilerplateResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BoilerplateResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BoilerplateResult& from) { BoilerplateResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BoilerplateResult* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "boilerplate.v1.BoilerplateResult"; }

  explicit BoilerplateResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BoilerplateResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BoilerplateResult& from);
  BoilerplateResult(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BoilerplateResult&& from) noexcept
      : BoilerplateResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPrintedLenFieldNumber = 1,
  };
  // uint32 printed_len = 1;
  void clear_printed_len() ;
  ::uint32_t printed_len() const;
  void set_printed_len(::uint32_t value);

  private:
  ::uint32_t _internal_printed_len() const;
  void _internal_set_printed_len(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:boilerplate.v1.BoilerplateResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BoilerplateResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t printed_len_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fexample_2fboilerplate_2fv1_2fboilerplate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BoilerplateResult_class_data_;
// -------------------------------------------------------------------

class Boilerplate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:boilerplate.v1.Boilerplate) */ {
 public:
  inline Boilerplate() : Boilerplate(nullptr) {}
  ~Boilerplate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Boilerplate* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Boilerplate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Boilerplate(::google::protobuf::internal::ConstantInitialized);

  inline Boilerplate(const Boilerplate& from) : Boilerplate(nullptr, from) {}
  inline Boilerplate(Boilerplate&& from) noexcept
      : Boilerplate(nullptr, ::std::move(from)) {}
  inline Boilerplate& operator=(const Boilerplate& from) {
    CopyFrom(from);
    return *this;
  }
  inline Boilerplate& operator=(Boilerplate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Boilerplate& default_instance() {
    return *reinterpret_cast<const Boilerplate*>(
        &_Boilerplate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Boilerplate& a, Boilerplate& b) { a.Swap(&b); }
  inline void Swap(Boilerplate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Boilerplate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Boilerplate* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Boilerplate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Boilerplate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Boilerplate& from) { Boilerplate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Boilerplate* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "boilerplate.v1.Boilerplate"; }

  explicit Boilerplate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Boilerplate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Boilerplate& from);
  Boilerplate(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Boilerplate&& from) noexcept
      : Boilerplate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageTextFieldNumber = 1,
  };
  // string message_text = 1;
  void clear_message_text() ;
  const ::std::string& message_text() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message_text(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message_text();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message_text();
  void set_allocated_message_text(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_message_text() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message_text(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message_text();

  public:
  // @@protoc_insertion_point(class_scope:boilerplate.v1.Boilerplate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 47,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Boilerplate& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr message_text_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fexample_2fboilerplate_2fv1_2fboilerplate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Boilerplate_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Boilerplate

// string message_text = 1;
inline void Boilerplate::clear_message_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_text_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Boilerplate::message_text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:boilerplate.v1.Boilerplate.message_text)
  return _internal_message_text();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Boilerplate::set_message_text(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.message_text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:boilerplate.v1.Boilerplate.message_text)
}
inline ::std::string* PROTOBUF_NONNULL Boilerplate::mutable_message_text()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_message_text();
  // @@protoc_insertion_point(field_mutable:boilerplate.v1.Boilerplate.message_text)
  return _s;
}
inline const ::std::string& Boilerplate::_internal_message_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_text_.Get();
}
inline void Boilerplate::_internal_set_message_text(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_text_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Boilerplate::_internal_mutable_message_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_text_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Boilerplate::release_message_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:boilerplate.v1.Boilerplate.message_text)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.message_text_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_text_.Set("", GetArena());
  }
  return released;
}
inline void Boilerplate::set_allocated_message_text(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.message_text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_text_.IsDefault()) {
    _impl_.message_text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:boilerplate.v1.Boilerplate.message_text)
}

// -------------------------------------------------------------------

// BoilerplateResult

// uint32 printed_len = 1;
inline void BoilerplateResult::clear_printed_len() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.printed_len_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t BoilerplateResult::printed_len() const {
  // @@protoc_insertion_point(field_get:boilerplate.v1.BoilerplateResult.printed_len)
  return _internal_printed_len();
}
inline void BoilerplateResult::set_printed_len(::uint32_t value) {
  _internal_set_printed_len(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:boilerplate.v1.BoilerplateResult.printed_len)
}
inline ::uint32_t BoilerplateResult::_internal_printed_len() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.printed_len_;
}
inline void BoilerplateResult::_internal_set_printed_len(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.printed_len_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace boilerplate


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2fcontrollerbus_2fexample_2fboilerplate_2fv1_2fboilerplate_2eproto_2epb_2eh
