// @generated
// This file is @generated by prost-build.
/// ExecControllerRequest is a protobuf request to execute a controller.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecControllerRequest {
    /// ConfigSet is the controller config set to execute.
    #[prost(message, optional, tag="1")]
    pub config_set: ::core::option::Option<super::super::configset::proto::ConfigSet>,
    /// ConfigSetYaml is optionally the YAML form of config_set to parse.
    /// Merged with config_set.
    #[prost(string, tag="2")]
    pub config_set_yaml: ::prost::alloc::string::String,
    /// ConfigSetYamlOverwrite sets if the yaml portion overwrites the proto portion.
    #[prost(bool, tag="3")]
    pub config_set_yaml_overwrite: bool,
}
/// ExecControllerResponse is a protobuf response stream.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecControllerResponse {
    /// Id is the configset identifier for this status report.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Status is the controller execution status.
    #[prost(enumeration="ControllerStatus", tag="2")]
    pub status: i32,
    /// ControllerInfo may contain the running controller info.
    #[prost(message, optional, tag="3")]
    pub controller_info: ::core::option::Option<super::Info>,
    /// ErrorInfo may contain the error information.
    #[prost(string, tag="4")]
    pub error_info: ::prost::alloc::string::String,
}
/// ControllerStatus holds basic status for a controller.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ControllerStatus {
    /// ControllerStatus_UNKNOWN is unrecognized.
    Unknown = 0,
    /// ControllerStatus_CONFIGURING indicates the controller is configuring.
    Configuring = 1,
    /// ControllerStatus_RUNNING indicates the controller is running.
    Running = 2,
    /// ControllerStatus_ERROR indicates the controller is terminated with an error.
    Error = 3,
}
impl ControllerStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ControllerStatus_UNKNOWN",
            Self::Configuring => "ControllerStatus_CONFIGURING",
            Self::Running => "ControllerStatus_RUNNING",
            Self::Error => "ControllerStatus_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ControllerStatus_UNKNOWN" => Some(Self::Unknown),
            "ControllerStatus_CONFIGURING" => Some(Self::Configuring),
            "ControllerStatus_RUNNING" => Some(Self::Running),
            "ControllerStatus_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
