//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/controllerbus/controller/exec/exec.proto
// Protobuf C++ Version: 6.33.4

#include "exec.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace controller {
namespace exec {

inline constexpr ExecControllerResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_info_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        controller_info_{nullptr},
        status_{static_cast< ::controller::exec::ControllerStatus >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR ExecControllerResponse::ExecControllerResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ExecControllerResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ExecControllerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExecControllerResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExecControllerResponseDefaultTypeInternal() {}
  union {
    ExecControllerResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExecControllerResponseDefaultTypeInternal _ExecControllerResponse_default_instance_;

inline constexpr ExecControllerRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        config_set_yaml_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        config_set_{nullptr},
        config_set_yaml_overwrite_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ExecControllerRequest::ExecControllerRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ExecControllerRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ExecControllerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExecControllerRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExecControllerRequestDefaultTypeInternal() {}
  union {
    ExecControllerRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExecControllerRequestDefaultTypeInternal _ExecControllerRequest_default_instance_;
}  // namespace exec
}  // namespace controller
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerRequest, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerRequest, _impl_.config_set_),
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerRequest, _impl_.config_set_yaml_),
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerRequest, _impl_.config_set_yaml_overwrite_),
        1,
        0,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerResponse, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerResponse, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerResponse, _impl_.controller_info_),
        PROTOBUF_FIELD_OFFSET(::controller::exec::ExecControllerResponse, _impl_.error_info_),
        0,
        3,
        2,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::controller::exec::ExecControllerRequest)},
        {9, sizeof(::controller::exec::ExecControllerResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::controller::exec::_ExecControllerRequest_default_instance_._instance,
    &::controller::exec::_ExecControllerResponse_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\nDgithub.com/aperturerobotics/controller"
    "bus/controller/exec/exec.proto\022\017controll"
    "er.exec\032Egithub.com/aperturerobotics/con"
    "trollerbus/controller/controller.proto\032T"
    "github.com/aperturerobotics/controllerbu"
    "s/controller/configset/proto/configset.p"
    "roto\"\203\001\n\025ExecControllerRequest\022.\n\nconfig"
    "_set\030\001 \001(\0132\032.configset.proto.ConfigSet\022\027"
    "\n\017config_set_yaml\030\002 \001(\t\022!\n\031config_set_ya"
    "ml_overwrite\030\003 \001(\010\"\226\001\n\026ExecControllerRes"
    "ponse\022\n\n\002id\030\001 \001(\t\0221\n\006status\030\002 \001(\0162!.cont"
    "roller.exec.ControllerStatus\022)\n\017controll"
    "er_info\030\003 \001(\0132\020.controller.Info\022\022\n\nerror"
    "_info\030\004 \001(\t*\214\001\n\020ControllerStatus\022\034\n\030Cont"
    "rollerStatus_UNKNOWN\020\000\022 \n\034ControllerStat"
    "us_CONFIGURING\020\001\022\034\n\030ControllerStatus_RUN"
    "NING\020\002\022\032\n\026ControllerStatus_ERROR\020\003b\006prot"
    "o3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto_deps[2] = {
        &::descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fconfigset_2fproto_2fconfigset_2eproto,
        &::descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fcontroller_2eproto,
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto = {
    false,
    false,
    682,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto,
    "github.com/aperturerobotics/controllerbus/controller/exec/exec.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto_once,
    descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto_deps,
    2,
    2,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto,
};
namespace controller {
namespace exec {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ControllerStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto);
  return file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ControllerStatus_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class ExecControllerRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ExecControllerRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_._has_bits_);
};

void ExecControllerRequest::clear_config_set() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.config_set_ != nullptr) _impl_.config_set_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
ExecControllerRequest::ExecControllerRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ExecControllerRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.exec.ExecControllerRequest)
}
PROTOBUF_NDEBUG_INLINE ExecControllerRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::controller::exec::ExecControllerRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        config_set_yaml_(arena, from.config_set_yaml_) {}

ExecControllerRequest::ExecControllerRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ExecControllerRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ExecControllerRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ExecControllerRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.config_set_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.config_set_)
                : nullptr;
  _impl_.config_set_yaml_overwrite_ = from._impl_.config_set_yaml_overwrite_;

  // @@protoc_insertion_point(copy_constructor:controller.exec.ExecControllerRequest)
}
PROTOBUF_NDEBUG_INLINE ExecControllerRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        config_set_yaml_(arena) {}

inline void ExecControllerRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, config_set_),
           0,
           offsetof(Impl_, config_set_yaml_overwrite_) -
               offsetof(Impl_, config_set_) +
               sizeof(Impl_::config_set_yaml_overwrite_));
}
ExecControllerRequest::~ExecControllerRequest() {
  // @@protoc_insertion_point(destructor:controller.exec.ExecControllerRequest)
  SharedDtor(*this);
}
inline void ExecControllerRequest::SharedDtor(MessageLite& self) {
  ExecControllerRequest& this_ = static_cast<ExecControllerRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.config_set_yaml_.Destroy();
  delete this_._impl_.config_set_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ExecControllerRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ExecControllerRequest(arena);
}
constexpr auto ExecControllerRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ExecControllerRequest),
                                            alignof(ExecControllerRequest));
}
constexpr auto ExecControllerRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ExecControllerRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ExecControllerRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ExecControllerRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ExecControllerRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ExecControllerRequest>(), &ExecControllerRequest::ByteSizeLong,
              &ExecControllerRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_._cached_size_),
          false,
      },
      &ExecControllerRequest::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ExecControllerRequest_class_data_ =
        ExecControllerRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ExecControllerRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ExecControllerRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ExecControllerRequest_class_data_.tc_table);
  return ExecControllerRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 61, 2>
ExecControllerRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ExecControllerRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::exec::ExecControllerRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .configset.proto.ConfigSet config_set = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_.config_set_)}},
    // string config_set_yaml = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_.config_set_yaml_)}},
    // bool config_set_yaml_overwrite = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ExecControllerRequest, _impl_.config_set_yaml_overwrite_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_.config_set_yaml_overwrite_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .configset.proto.ConfigSet config_set = 1;
    {PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_.config_set_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string config_set_yaml = 2;
    {PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_.config_set_yaml_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool config_set_yaml_overwrite = 3;
    {PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_.config_set_yaml_overwrite_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::configset::proto::ConfigSet>()},
  }},
  {{
    "\45\0\17\0\0\0\0\0"
    "controller.exec.ExecControllerRequest"
    "config_set_yaml"
  }},
};
PROTOBUF_NOINLINE void ExecControllerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.exec.ExecControllerRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.config_set_yaml_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.config_set_ != nullptr);
      _impl_.config_set_->Clear();
    }
  }
  _impl_.config_set_yaml_overwrite_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ExecControllerRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ExecControllerRequest& this_ = static_cast<const ExecControllerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ExecControllerRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ExecControllerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:controller.exec.ExecControllerRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .configset.proto.ConfigSet config_set = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.config_set_, this_._impl_.config_set_->GetCachedSize(), target,
        stream);
  }

  // string config_set_yaml = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_config_set_yaml().empty()) {
      const ::std::string& _s = this_._internal_config_set_yaml();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "controller.exec.ExecControllerRequest.config_set_yaml");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // bool config_set_yaml_overwrite = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_config_set_yaml_overwrite() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_config_set_yaml_overwrite(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:controller.exec.ExecControllerRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ExecControllerRequest::ByteSizeLong(const MessageLite& base) {
  const ExecControllerRequest& this_ = static_cast<const ExecControllerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ExecControllerRequest::ByteSizeLong() const {
  const ExecControllerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:controller.exec.ExecControllerRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string config_set_yaml = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_config_set_yaml().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_config_set_yaml());
      }
    }
    // .configset.proto.ConfigSet config_set = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.config_set_);
    }
    // bool config_set_yaml_overwrite = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_config_set_yaml_overwrite() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ExecControllerRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ExecControllerRequest*>(&to_msg);
  auto& from = static_cast<const ExecControllerRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.exec.ExecControllerRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_config_set_yaml().empty()) {
        _this->_internal_set_config_set_yaml(from._internal_config_set_yaml());
      } else {
        if (_this->_impl_.config_set_yaml_.IsDefault()) {
          _this->_internal_set_config_set_yaml("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.config_set_ != nullptr);
      if (_this->_impl_.config_set_ == nullptr) {
        _this->_impl_.config_set_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.config_set_);
      } else {
        _this->_impl_.config_set_->MergeFrom(*from._impl_.config_set_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_config_set_yaml_overwrite() != 0) {
        _this->_impl_.config_set_yaml_overwrite_ = from._impl_.config_set_yaml_overwrite_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ExecControllerRequest::CopyFrom(const ExecControllerRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:controller.exec.ExecControllerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ExecControllerRequest::InternalSwap(ExecControllerRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.config_set_yaml_, &other->_impl_.config_set_yaml_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_.config_set_yaml_overwrite_)
      + sizeof(ExecControllerRequest::_impl_.config_set_yaml_overwrite_)
      - PROTOBUF_FIELD_OFFSET(ExecControllerRequest, _impl_.config_set_)>(
          reinterpret_cast<char*>(&_impl_.config_set_),
          reinterpret_cast<char*>(&other->_impl_.config_set_));
}

::google::protobuf::Metadata ExecControllerRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ExecControllerResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ExecControllerResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_._has_bits_);
};

void ExecControllerResponse::clear_controller_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.controller_info_ != nullptr) _impl_.controller_info_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
ExecControllerResponse::ExecControllerResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ExecControllerResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.exec.ExecControllerResponse)
}
PROTOBUF_NDEBUG_INLINE ExecControllerResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::controller::exec::ExecControllerResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_),
        error_info_(arena, from.error_info_) {}

ExecControllerResponse::ExecControllerResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ExecControllerResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ExecControllerResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ExecControllerResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.controller_info_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.controller_info_)
                : nullptr;
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:controller.exec.ExecControllerResponse)
}
PROTOBUF_NDEBUG_INLINE ExecControllerResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena),
        error_info_(arena) {}

inline void ExecControllerResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, controller_info_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, controller_info_) +
               sizeof(Impl_::status_));
}
ExecControllerResponse::~ExecControllerResponse() {
  // @@protoc_insertion_point(destructor:controller.exec.ExecControllerResponse)
  SharedDtor(*this);
}
inline void ExecControllerResponse::SharedDtor(MessageLite& self) {
  ExecControllerResponse& this_ = static_cast<ExecControllerResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.error_info_.Destroy();
  delete this_._impl_.controller_info_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ExecControllerResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ExecControllerResponse(arena);
}
constexpr auto ExecControllerResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ExecControllerResponse),
                                            alignof(ExecControllerResponse));
}
constexpr auto ExecControllerResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ExecControllerResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ExecControllerResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ExecControllerResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ExecControllerResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ExecControllerResponse>(), &ExecControllerResponse::ByteSizeLong,
              &ExecControllerResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_._cached_size_),
          false,
      },
      &ExecControllerResponse::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ExecControllerResponse_class_data_ =
        ExecControllerResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ExecControllerResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ExecControllerResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ExecControllerResponse_class_data_.tc_table);
  return ExecControllerResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 59, 2>
ExecControllerResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ExecControllerResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::exec::ExecControllerResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error_info = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.error_info_)}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.id_)}},
    // .controller.exec.ControllerStatus status = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ExecControllerResponse, _impl_.status_), 3>(),
     {16, 3, 0,
      PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.status_)}},
    // .controller.Info controller_info = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.controller_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .controller.exec.ControllerStatus status = 2;
    {PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.status_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .controller.Info controller_info = 3;
    {PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.controller_info_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string error_info = 4;
    {PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.error_info_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::controller::Info>()},
  }},
  {{
    "\46\2\0\0\12\0\0\0"
    "controller.exec.ExecControllerResponse"
    "id"
    "error_info"
  }},
};
PROTOBUF_NOINLINE void ExecControllerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.exec.ExecControllerResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.error_info_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.controller_info_ != nullptr);
      _impl_.controller_info_->Clear();
    }
  }
  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ExecControllerResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ExecControllerResponse& this_ = static_cast<const ExecControllerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ExecControllerResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ExecControllerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:controller.exec.ExecControllerResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_id().empty()) {
      const ::std::string& _s = this_._internal_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "controller.exec.ExecControllerResponse.id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .controller.exec.ControllerStatus status = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_status(), target);
    }
  }

  // .controller.Info controller_info = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.controller_info_, this_._impl_.controller_info_->GetCachedSize(), target,
        stream);
  }

  // string error_info = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_error_info().empty()) {
      const ::std::string& _s = this_._internal_error_info();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "controller.exec.ExecControllerResponse.error_info");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:controller.exec.ExecControllerResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ExecControllerResponse::ByteSizeLong(const MessageLite& base) {
  const ExecControllerResponse& this_ = static_cast<const ExecControllerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ExecControllerResponse::ByteSizeLong() const {
  const ExecControllerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:controller.exec.ExecControllerResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_id());
      }
    }
    // string error_info = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_error_info().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_error_info());
      }
    }
    // .controller.Info controller_info = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.controller_info_);
    }
    // .controller.exec.ControllerStatus status = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ExecControllerResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ExecControllerResponse*>(&to_msg);
  auto& from = static_cast<const ExecControllerResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.exec.ExecControllerResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_id().empty()) {
        _this->_internal_set_id(from._internal_id());
      } else {
        if (_this->_impl_.id_.IsDefault()) {
          _this->_internal_set_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_error_info().empty()) {
        _this->_internal_set_error_info(from._internal_error_info());
      } else {
        if (_this->_impl_.error_info_.IsDefault()) {
          _this->_internal_set_error_info("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.controller_info_ != nullptr);
      if (_this->_impl_.controller_info_ == nullptr) {
        _this->_impl_.controller_info_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.controller_info_);
      } else {
        _this->_impl_.controller_info_->MergeFrom(*from._impl_.controller_info_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ExecControllerResponse::CopyFrom(const ExecControllerResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:controller.exec.ExecControllerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ExecControllerResponse::InternalSwap(ExecControllerResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_info_, &other->_impl_.error_info_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.status_)
      + sizeof(ExecControllerResponse::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(ExecControllerResponse, _impl_.controller_info_)>(
          reinterpret_cast<char*>(&_impl_.controller_info_),
          reinterpret_cast<char*>(&other->_impl_.controller_info_));
}

::google::protobuf::Metadata ExecControllerResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace exec
}  // namespace controller
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fcontrollerbus_2fcontroller_2fexec_2fexec_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
