// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/controllerbus/example/boilerplate/config.proto

package boilerplate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config is the boilerplate configuration.
type Config struct {
	// ExampleField is an example configuration field.
	ExampleField         string   `protobuf:"bytes,1,opt,name=example_field,json=exampleField,proto3" json:"example_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b79854f50ab81aa, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetExampleField() string {
	if m != nil {
		return m.ExampleField
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "boilerplate.Config")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/controllerbus/example/boilerplate/config.proto", fileDescriptor_2b79854f50ab81aa)
}

var fileDescriptor_2b79854f50ab81aa = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xf2, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x48, 0x2d, 0x2a, 0x29, 0x2d, 0x4a, 0x2d,
	0xca, 0x4f, 0xca, 0x2f, 0xc9, 0x4c, 0x2e, 0xd6, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0xc9,
	0x49, 0x2d, 0x4a, 0x2a, 0x2d, 0xd6, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x4f, 0xca,
	0xcf, 0xcc, 0x49, 0x2d, 0x2a, 0xc8, 0x49, 0x2c, 0x49, 0x05, 0xa9, 0x48, 0xcb, 0x4c, 0xd7, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46, 0x92, 0x51, 0xd2, 0xe5, 0x62, 0x73, 0x06, 0x4b, 0x0a,
	0x29, 0x73, 0xf1, 0x42, 0xb5, 0xc6, 0xa7, 0x65, 0xa6, 0xe6, 0xa4, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0xf1, 0x40, 0x05, 0xdd, 0x40, 0x62, 0x49, 0x6c, 0x60, 0x23, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x98, 0x6d, 0x84, 0xaa, 0x90, 0x00, 0x00, 0x00,
}
