// @generated by protoc-gen-es v1.8.0 with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/controllerbus/config/config.proto (package config, syntax proto3)
/* eslint-disable */

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf'
import { Message, proto3 } from '@bufbuild/protobuf'

/**
 * Placeholder is a config used for type assertions.
 *
 * @generated from message config.Placeholder
 */
export class Placeholder extends Message<Placeholder> {
  constructor(data?: PartialMessage<Placeholder>) {
    super()
    proto3.util.initPartial(data, this)
  }

  static readonly runtime: typeof proto3 = proto3
  static readonly typeName = 'config.Placeholder'
  static readonly fields: FieldList = proto3.util.newFieldList(() => [])

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): Placeholder {
    return new Placeholder().fromBinary(bytes, options)
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): Placeholder {
    return new Placeholder().fromJson(jsonValue, options)
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): Placeholder {
    return new Placeholder().fromJsonString(jsonString, options)
  }

  static equals(
    a: Placeholder | PlainMessage<Placeholder> | undefined,
    b: Placeholder | PlainMessage<Placeholder> | undefined,
  ): boolean {
    return proto3.util.equals(Placeholder, a, b)
  }
}
