// @generated
// This file is @generated by prost-build.
/// Config is the boilerplate configuration.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    /// ExitAfterDur requests an os.Exit(0) after a duration.
    #[prost(string, tag="1")]
    pub exit_after_dur: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
