// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/controllerbus/example/plugin-demo/demo-controller/config.proto

package hot_compile_demo_controller

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config is the boilerplate configuration.
type Config struct {
	// ExitAfterDur requests an os.Exit(0) after a duration.
	ExitAfterDur         string   `protobuf:"bytes,1,opt,name=exit_after_dur,json=exitAfterDur,proto3" json:"exit_after_dur,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e54ce1baae84e5, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetExitAfterDur() string {
	if m != nil {
		return m.ExitAfterDur
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "hot.compile.demo.controller.Config")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/controllerbus/example/plugin-demo/demo-controller/config.proto", fileDescriptor_41e54ce1baae84e5)
}

var fileDescriptor_41e54ce1baae84e5 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcc, 0xb1, 0x0a, 0x83, 0x40,
	0x0c, 0xc6, 0x71, 0x5c, 0x84, 0x4a, 0xe9, 0xe0, 0x54, 0xe8, 0x52, 0x4a, 0x87, 0x2e, 0xde, 0x0d,
	0x7d, 0x82, 0xd2, 0x3e, 0x41, 0xc7, 0x2e, 0xe2, 0x69, 0xd4, 0xc0, 0x69, 0x8e, 0x98, 0x80, 0x8f,
	0x5f, 0xe2, 0xe2, 0x92, 0xe1, 0xe3, 0x97, 0x7f, 0xf1, 0x1b, 0x50, 0x46, 0x0d, 0xae, 0xa5, 0xc9,
	0x37, 0x09, 0x58, 0x94, 0x81, 0x29, 0x90, 0x60, 0xbb, 0xf8, 0x96, 0x66, 0x61, 0x8a, 0x11, 0x38,
	0xe8, 0xe2, 0x61, 0x6d, 0xa6, 0x14, 0xc1, 0xa7, 0xa8, 0x03, 0xce, 0x55, 0x07, 0x13, 0x79, 0x3b,
	0xd5, 0xce, 0xec, 0xa3, 0xc7, 0xc1, 0x25, 0x26, 0xa1, 0xf2, 0x32, 0x92, 0x58, 0x38, 0x61, 0x04,
	0x67, 0xd2, 0xed, 0xf2, 0xe6, 0x8a, 0xfc, 0xbd, 0xe1, 0xf2, 0x5e, 0x9c, 0x60, 0x45, 0xa9, 0x9b,
	0x5e, 0x80, 0xeb, 0x4e, 0xf9, 0x9c, 0x5d, 0xb3, 0xc7, 0xe1, 0x7b, 0xb4, 0xf5, 0x65, 0xe3, 0x47,
	0x39, 0xe4, 0x5b, 0xf3, 0xf9, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xbb, 0x66, 0x96, 0xb1, 0x00,
	0x00, 0x00,
}
