// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/controllerbus/example/boilerplate/controller/config.proto (package boilerplate.controller, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from "@aptre/protobuf-es-lite";
import { createMessageType, Message } from "@aptre/protobuf-es-lite";

export const protobufPackage = "boilerplate.controller";

/**
 * Config is the boilerplate configuration.
 *
 * @generated from message boilerplate.controller.Config
 */
export type Config = Message<{
  /**
   * ExampleField is an example configuration field.
   *
   * @generated from field: string example_field = 1;
   */
  exampleField?: string;
  /**
   * FailWithErr indicates the controller should fail with the given error.
   *
   * @generated from field: string fail_with_err = 2;
   */
  failWithErr?: string;

}>;

export const Config: MessageType<Config> = createMessageType(
  {
    typeName: "boilerplate.controller.Config",
    fields: [
        { no: 1, name: "example_field", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "fail_with_err", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ] as readonly PartialFieldInfo[],
    packedByDefault: true,
  },
);

