// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/controllerbus/plugin/loader/shared-library/filesystem/config.proto

package plugin_loader_filesystem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config is configuration for the filesystem hot-plugin loader.
type Config struct {
	// Dir is the directory to load from.
	Dir string `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	// Watch will watch the directory and hot-reload plugins.
	Watch                bool     `protobuf:"varint,2,opt,name=watch,proto3" json:"watch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_60bbb82496843f53, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *Config) GetWatch() bool {
	if m != nil {
		return m.Watch
	}
	return false
}

func init() {
	proto.RegisterType((*Config)(nil), "plugin.loader.filesystem.Config")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/controllerbus/plugin/loader/shared-library/filesystem/config.proto", fileDescriptor_60bbb82496843f53)
}

var fileDescriptor_60bbb82496843f53 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcc, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0xc6, 0x71, 0x2c, 0x92, 0xda, 0x53, 0x48, 0x07, 0x8f, 0xd2, 0xc9, 0x4b, 0xbb, 0x41, 0x8f,
	0xd0, 0x1b, 0xf8, 0x00, 0xc1, 0xee, 0x3a, 0xea, 0xc0, 0xea, 0xc8, 0xec, 0x2c, 0xe1, 0xdb, 0x87,
	0x7a, 0xe8, 0x36, 0x03, 0xff, 0xdf, 0xa7, 0x3e, 0x3d, 0xca, 0x90, 0x9c, 0xf6, 0x34, 0x1a, 0x3b,
	0x03, 0x4b, 0x62, 0x60, 0x72, 0x24, 0xe8, 0xa3, 0xf1, 0x34, 0x09, 0x53, 0x08, 0xc0, 0x2e, 0x45,
	0x33, 0x87, 0xd4, 0xe3, 0x64, 0x02, 0xd9, 0x16, 0xd8, 0xc4, 0xc1, 0x32, 0xb4, 0x8f, 0x80, 0x8e,
	0x2d, 0x2f, 0xa6, 0xc3, 0x00, 0x71, 0x89, 0x02, 0xe3, 0xaa, 0x3a, 0xec, 0xf5, 0xcc, 0x24, 0x54,
	0x94, 0xbb, 0xd2, 0xbb, 0xd2, 0xff, 0xec, 0xfe, 0x54, 0xf9, 0x7b, 0x2b, 0x8b, 0xab, 0x3a, 0xb6,
	0xc8, 0x65, 0x56, 0x65, 0xf5, 0xa5, 0x59, 0xcf, 0xe2, 0xa6, 0x4e, 0x5f, 0x2b, 0x7e, 0x28, 0x0f,
	0x55, 0x56, 0x9f, 0x9b, 0xfd, 0x71, 0xf9, 0x36, 0xf9, 0xfa, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa9,
	0xca, 0x51, 0x92, 0xb4, 0x00, 0x00, 0x00,
}
