// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/controllerbus/example/hello-world/controller.proto (package main, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import { createMessageType, Message, ScalarType } from '@aptre/protobuf-es-lite'

export const protobufPackage = 'main'

/**
 * ToyControllerConfig contains configuration for the toy controller.
 *
 * @generated from message main.ToyControllerConfig
 */
export type ToyControllerConfig = Message<{
  /**
   * Name is the name to say hello to.
   *
   * @generated from field: string name = 1;
   */
  name?: string
}>

// ToyControllerConfig contains the message type declaration for ToyControllerConfig.
export const ToyControllerConfig: MessageType<ToyControllerConfig> =
  createMessageType({
    typeName: 'main.ToyControllerConfig',
    fields: [
      { no: 1, name: 'name', kind: 'scalar', T: ScalarType.STRING },
    ] as readonly PartialFieldInfo[],
    packedByDefault: true,
  })
