// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/controllerbus/example/hello-world/controller.proto

package main

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ToyControllerConfig contains configuration for the toy controller.
type ToyControllerConfig struct {
	// Name is the name to say hello to.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToyControllerConfig) Reset()         { *m = ToyControllerConfig{} }
func (m *ToyControllerConfig) String() string { return proto.CompactTextString(m) }
func (*ToyControllerConfig) ProtoMessage()    {}
func (*ToyControllerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_54b18112696c06aa, []int{0}
}

func (m *ToyControllerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToyControllerConfig.Unmarshal(m, b)
}
func (m *ToyControllerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToyControllerConfig.Marshal(b, m, deterministic)
}
func (m *ToyControllerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToyControllerConfig.Merge(m, src)
}
func (m *ToyControllerConfig) XXX_Size() int {
	return xxx_messageInfo_ToyControllerConfig.Size(m)
}
func (m *ToyControllerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ToyControllerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ToyControllerConfig proto.InternalMessageInfo

func (m *ToyControllerConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ToyControllerConfig)(nil), "main.ToyControllerConfig")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/controllerbus/example/hello-world/controller.proto", fileDescriptor_54b18112696c06aa)
}

var fileDescriptor_54b18112696c06aa = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xf2, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x48, 0x2d, 0x2a, 0x29, 0x2d, 0x4a, 0x2d,
	0xca, 0x4f, 0xca, 0x2f, 0xc9, 0x4c, 0x2e, 0xd6, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0xc9,
	0x49, 0x2d, 0x4a, 0x2a, 0x2d, 0xd6, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0xcf, 0x48,
	0xcd, 0xc9, 0xc9, 0xd7, 0x2d, 0xcf, 0x2f, 0xca, 0x49, 0x41, 0x52, 0xa1, 0x57, 0x50, 0x94, 0x5f,
	0x92, 0x2f, 0xc4, 0x92, 0x9b, 0x98, 0x99, 0xa7, 0xa4, 0xc9, 0x25, 0x1c, 0x92, 0x5f, 0xe9, 0x0c,
	0x97, 0x74, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x17, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0xfa, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc3, 0xab, 0xb1, 0x9e, 0x89, 0x00, 0x00, 0x00,
}
