// @generated
// This file is @generated by prost-build.
/// Info contains information about a controller.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Info {
    /// Id contains the identifier of the controller.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Version contains the version string for the controller.
    #[prost(string, tag="2")]
    pub version: ::prost::alloc::string::String,
    /// Description contains a descriptive string about the controller.
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
