// @generated
// This file is @generated by prost-build.
/// DirectiveInfo contains directive information in protobuf form.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirectiveInfo {
    /// Name is the directive name.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// DebugVals contains the directive debug values.
    #[prost(message, repeated, tag="2")]
    pub debug_vals: ::prost::alloc::vec::Vec<ProtoDebugValue>,
}
/// DirectiveState contains directive info and state info in protobuf form.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirectiveState {
    /// Info is the directive info.
    ///
    /// TODO result info
    #[prost(message, optional, tag="1")]
    pub info: ::core::option::Option<DirectiveInfo>,
}
/// ProtoDebugValue is a debug value.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProtoDebugValue {
    /// Key is the debug value key.
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    /// Values are the debug value values.
    #[prost(string, repeated, tag="2")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
