// @generated
// This file is @generated by prost-build.
/// ConfigSet contains a configuration set.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigSet {
    /// Configs contains the controller configurations.
    #[prost(map="string, message", tag="1")]
    pub configs: ::std::collections::HashMap<::prost::alloc::string::String, ControllerConfig>,
}
/// ControllerConfig contains a controller configuration.
///
/// protobuf-go-lite:disable-json
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ControllerConfig {
    /// Id is the config ID.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Rev is the revision number of the configuration.
    #[prost(uint64, tag="2")]
    pub rev: u64,
    /// Config is the configuration object.
    /// Proto supports: protobuf (binary) and json (starting with {).
    /// Json supports: protobuf (base64) and json (inline object).
    #[prost(bytes="vec", tag="3")]
    pub config: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
