// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/controllerbus/controller/configset/proto/configset.proto (package configset.proto, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import { createMessageType, Message, ScalarType } from '@aptre/protobuf-es-lite'

export const protobufPackage = 'configset.proto'

/**
 * ControllerConfig contains a controller configuration.
 *
 * protobuf-go-lite:disable-json
 *
 * @generated from message configset.proto.ControllerConfig
 */
export type ControllerConfig = Message<{
  /**
   * Id is the config ID.
   *
   * @generated from field: string id = 1;
   */
  id?: string
  /**
   * Rev is the revision number of the configuration.
   *
   * @generated from field: uint64 rev = 2;
   */
  rev?: bigint
  /**
   * Config is the configuration object.
   * Proto supports: protobuf (binary) and json (starting with {).
   * Json supports: protobuf (base64) and json (inline object).
   *
   * @generated from field: bytes config = 3;
   */
  config?: Uint8Array
}>

// ControllerConfig contains the message type declaration for ControllerConfig.
export const ControllerConfig: MessageType<ControllerConfig> =
  createMessageType({
    typeName: 'configset.proto.ControllerConfig',
    fields: [
      { no: 1, name: 'id', kind: 'scalar', T: ScalarType.STRING },
      { no: 2, name: 'rev', kind: 'scalar', T: ScalarType.UINT64 },
      { no: 3, name: 'config', kind: 'scalar', T: ScalarType.BYTES },
    ] as readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * ConfigSet contains a configuration set.
 *
 * @generated from message configset.proto.ConfigSet
 */
export type ConfigSet = Message<{
  /**
   * Configs contains the controller configurations.
   *
   * @generated from field: map<string, configset.proto.ControllerConfig> configs = 1;
   */
  configs?: { [key: string]: ControllerConfig }
}>

// ConfigSet contains the message type declaration for ConfigSet.
export const ConfigSet: MessageType<ConfigSet> = createMessageType({
  typeName: 'configset.proto.ConfigSet',
  fields: [
    {
      no: 1,
      name: 'configs',
      kind: 'map',
      K: ScalarType.STRING,
      V: { kind: 'message', T: () => ControllerConfig },
    },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
